//
// Generated file, do not edit! Created by nedtool 5.6 from plexe/messages/BranchDirAck.msg.
//

#ifndef __BRANCHDIRACK_M_H
#define __BRANCHDIRACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/BranchDirAck.msg:31</tt> by nedtool.
 * <pre>
 * // Message from all vehicles in the Platoon to the leader to acknoledge the updated formation.
 * // Is similar to a PlatoonBeacon.
 * packet BranchDirAck extends ManeuverMessage
 * {
 *     int dest;
 * }
 * </pre>
 */
class PLEXE_API BranchDirAck : public ::ManeuverMessage
{
  protected:
    int dest;

  private:
    void copy(const BranchDirAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BranchDirAck&);

  public:
    BranchDirAck(const char *name=nullptr, short kind=0);
    BranchDirAck(const BranchDirAck& other);
    virtual ~BranchDirAck();
    BranchDirAck& operator=(const BranchDirAck& other);
    virtual BranchDirAck *dup() const override {return new BranchDirAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getDest() const;
    virtual void setDest(int dest);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BranchDirAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BranchDirAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BRANCHDIRACK_M_H

