//
// Generated file, do not edit! Created by nedtool 5.6 from plexe/messages/InsideSplitAreaAck.msg.
//

#ifndef __INSIDESPLITAREAACK_M_H
#define __INSIDESPLITAREAACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/InsideSplitAreaAck.msg:30</tt> by nedtool.
 * <pre>
 * // Notify the leader a follower changed lane.
 * // Is sent from follower to platoon leader.
 * packet InsideSplitAreaAck extends ManeuverMessage
 * {
 *     bool response;
 * }
 * </pre>
 */
class PLEXE_API InsideSplitAreaAck : public ::ManeuverMessage
{
  protected:
    bool response;

  private:
    void copy(const InsideSplitAreaAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InsideSplitAreaAck&);

  public:
    InsideSplitAreaAck(const char *name=nullptr, short kind=0);
    InsideSplitAreaAck(const InsideSplitAreaAck& other);
    virtual ~InsideSplitAreaAck();
    InsideSplitAreaAck& operator=(const InsideSplitAreaAck& other);
    virtual InsideSplitAreaAck *dup() const override {return new InsideSplitAreaAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getResponse() const;
    virtual void setResponse(bool response);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const InsideSplitAreaAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, InsideSplitAreaAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __INSIDESPLITAREAACK_M_H

