//
// Generated file, do not edit! Created by nedtool 5.6 from plexe/messages/MergePlatoonRequest.msg.
//

#ifndef __MERGEPLATOONREQUEST_M_H
#define __MERGEPLATOONREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "JoinPlatoonRequest_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/MergePlatoonRequest.msg:30</tt> by nedtool.
 * <pre>
 * // Request to merge two platoons
 * // Is sent from a leader to the leader of the Platoon to be merged with
 * packet MergePlatoonRequest extends JoinPlatoonRequest
 * {
 *     // list of members following the leader of the merging platoon
 *     int members[];
 * }
 * </pre>
 */
class PLEXE_API MergePlatoonRequest : public ::JoinPlatoonRequest
{
  protected:
    int *members; // array ptr
    unsigned int members_arraysize;

  private:
    void copy(const MergePlatoonRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MergePlatoonRequest&);

  public:
    MergePlatoonRequest(const char *name=nullptr, short kind=0);
    MergePlatoonRequest(const MergePlatoonRequest& other);
    virtual ~MergePlatoonRequest();
    MergePlatoonRequest& operator=(const MergePlatoonRequest& other);
    virtual MergePlatoonRequest *dup() const override {return new MergePlatoonRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setMembersArraySize(unsigned int size);
    virtual unsigned int getMembersArraySize() const;
    virtual int getMembers(unsigned int k) const;
    virtual void setMembers(unsigned int k, int members);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MergePlatoonRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MergePlatoonRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MERGEPLATOONREQUEST_M_H

