//
// Generated file, do not edit! Created by nedtool 5.6 from plexe/messages/StartSplitArea.msg.
//

#ifndef __STARTSPLITAREA_M_H
#define __STARTSPLITAREA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/StartSplitArea.msg:31</tt> by nedtool.
 * <pre>
 * // Notify the leader a follower changed lane.
 * // Is sent from follower to platoon leader.
 * packet StartSplitArea extends ManeuverMessage
 * {
 * }
 * </pre>
 */
class PLEXE_API StartSplitArea : public ::ManeuverMessage
{
  protected:

  private:
    void copy(const StartSplitArea& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StartSplitArea&);

  public:
    StartSplitArea(const char *name=nullptr, short kind=0);
    StartSplitArea(const StartSplitArea& other);
    virtual ~StartSplitArea();
    StartSplitArea& operator=(const StartSplitArea& other);
    virtual StartSplitArea *dup() const override {return new StartSplitArea(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StartSplitArea& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StartSplitArea& obj) {obj.parsimUnpack(b);}


#endif // ifndef __STARTSPLITAREA_M_H

