//
// Generated file, do not edit! Created by nedtool 5.6 from plexe/messages/StartSplit.msg.
//

#ifndef __STARTSPLIT_M_H
#define __STARTSPLIT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/StartSplit.msg:30</tt> by nedtool.
 * <pre>
 * // Advert that an abort is necessary.
 * // Is sent from a member to others.
 * packet StartSplit extends ManeuverMessage
 * {
 * }
 * </pre>
 */
class PLEXE_API StartSplit : public ::ManeuverMessage
{
  protected:

  private:
    void copy(const StartSplit& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StartSplit&);

  public:
    StartSplit(const char *name=nullptr, short kind=0);
    StartSplit(const StartSplit& other);
    virtual ~StartSplit();
    StartSplit& operator=(const StartSplit& other);
    virtual StartSplit *dup() const override {return new StartSplit(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StartSplit& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StartSplit& obj) {obj.parsimUnpack(b);}


#endif // ifndef __STARTSPLIT_M_H

