//
// Generated file, do not edit! Created by nedtool 5.6 from plexe/messages/UpdatePlatoonData.msg.
//

#ifndef __UPDATEPLATOONDATA_M_H
#define __UPDATEPLATOONDATA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "UpdatePlatoonFormation_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/UpdatePlatoonData.msg:30</tt> by nedtool.
 * <pre>
 * // Message to inform the all vehicles in the Platoon of the updated formation.
 * // Is similar to a PlatoonBeacon.
 * packet UpdatePlatoonData extends UpdatePlatoonFormation
 * {
 *     int newPlatoonId;
 * }
 * </pre>
 */
class PLEXE_API UpdatePlatoonData : public ::UpdatePlatoonFormation
{
  protected:
    int newPlatoonId;

  private:
    void copy(const UpdatePlatoonData& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdatePlatoonData&);

  public:
    UpdatePlatoonData(const char *name=nullptr, short kind=0);
    UpdatePlatoonData(const UpdatePlatoonData& other);
    virtual ~UpdatePlatoonData();
    UpdatePlatoonData& operator=(const UpdatePlatoonData& other);
    virtual UpdatePlatoonData *dup() const override {return new UpdatePlatoonData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNewPlatoonId() const;
    virtual void setNewPlatoonId(int newPlatoonId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UpdatePlatoonData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UpdatePlatoonData& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATEPLATOONDATA_M_H

